version: '3'
    services:
      database:
        image: "postgres:12" # use latest official postgres version
        name: "postgres12"
        env_file:
          - pg_database.env # configure postgres
        volumes:
          - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    volumes:
      database-data: # named volumes can be managed easier using docker-compose
      - ./host-folder/:/var/lib/postgresql/data/